name = "saphcc"                # имя воркера
main = "worker.js"             # путь к файлу воркера
compatibility_date = "2025-08-24"

[site]
bucket = "./app"               # папка с index.html и другими файлами
